
spring:
  application:
    name: eurekaServer
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka
    register-with-eureka: false
  server:
    enable-self-preservation: false